name: publish
on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{secrets.EXPO_TOKEN}}
      - run: yarn --frozen-lockfile
      - if: github.event_name == 'push'
        run: expo publish
      - if: github.event_name == 'pull_request'
        run: expo publish --release-channel=pr-${{github.event.number}}
      - if: github.event_name == 'pull_request'
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          msg: App is ready for review, you can [see it here](https://expo.dev/@friederbluemle/expotest04?release-channel=pr-${{github.event.number}}).
